Scikit inverse transform
neo-ai/tvm pull request #153
Opened 2020-10-16 22:59 UTC by yunma10

2020-10-19 21:44 UTC, trevor-m requested changes
Can you fix the formatting errors in the CI?

2020-10-19 21:44 UTC, trevor-m commented on tests/python/frontend/sklearn/test_forward.py
>  import tvm.topi.testing
Can you add `import tvm.testing`?

2020-10-21 23:27 UTC, yunma10 commented on tests/python/frontend/sklearn/test_forward.py
>  import tvm.topi.testing
Will do

2020-10-21 23:30 UTC, yunma10 commented on tests/python/frontend/sklearn/test_forward.py
>  import tvm.topi.testing
Should I actually delete import "tvm.topi.testing" and do "import tvm.testing"

2020-11-05 22:40 UTC, closed without merging